-- Create Super Admin Account
-- Run this in your PostgreSQL database

-- First, you need to hash the password
-- For "SecurePassword123!", the argon2 hash would be generated by the backend
-- So we'll use a simple approach - create via Prisma Studio or use this SQL with a hashed password

-- Option 1: Insert with placeholder password (you'll need to update with actual hash)
-- Generate hash by running in backend:
-- import { hashPassword } from './src/auth/password.js';
-- console.log(await hashPassword('SecurePassword123!'));

-- Example Insert (replace $HASHED_PASSWORD with actual hash):
INSERT INTO admins (
  id,
  email,
  username,
  "passwordHash",
  "fullName",
  "isSuperAdmin",
  "isActive",
  "createdAt",
  "updatedAt"
) VALUES (
  'cuid_' || floor(random() * 1000000)::text,
  'superadmin@genuinegrads.com',
  'superadmin',
  '$HASHED_PASSWORD', -- Replace this!
  'Super Admin',
  true, -- This makes it a super admin
  true,
  NOW(),
  NOW()
)
ON CONFLICT (email) DO NOTHING;

